### ISSUE TITLE
Transparency at the edge of the source image is messed up by PIL

### ISSUE THREAD

**Issue by paour** [twaddington/android-asset-resizer#15]
This source image [1] is resized to [2] (sorry about the light images), which leads to very bad edge corruption.

[Apparently](http://stackoverflow.com/a/6882161/304876), this is because PIL doesn't use premultiplied alpha for the resize and the solution is to manually perform the premult, and unpremult after resize.

[1] ![ic_menu_recording_on](https://cloud.githubusercontent.com/assets/90963/2596006/add45014-baa1-11e3-9b4a-572c733ace3e.png)

[2] ![ic_menu_recording_on](https://cloud.githubusercontent.com/assets/90963/2596008/b77ce55e-baa1-11e3-97f7-735bfedc3933.png)

**Comment by twaddington** [comment]
I'm not going to include special case handling like this into aaresize purely based on a random StackOverflow post. If someone with more experience with png alpha transparency wants to speak up about this that would be great but I'm not comfortable with this:

> I am also not very familiar with pre-multiplication, but StackOverflow has lots of posts on the subject
